package livingreadme

import (
	"fmt"
	"strings"
	"time"
)

// Meta carries the provenance a CI run stamps onto a generated region so a reader
// (or a diff reviewer) can tell when the numbers were produced and from which
// commit. All fields are optional; footer renders whatever is present.
type Meta struct {
	SHA      string    // git commit the results were produced from
	Ref      string    // git ref (branch/tag), informational
	When     time.Time // generation time; zero means "now" is not stamped
	Workflow string    // the CI workflow that produced the region, e.g. "benchmark"
}

// footer renders a single-line Markdown provenance note, e.g.
//
//	_Generated by the `benchmark` workflow from `a1b2c3d` on 2026-07-21._
//
// It always ends in a newline. With no metadata set it returns an empty string.
func (m Meta) footer() string {
	var parts []string
	if m.Workflow != "" {
		parts = append(parts, fmt.Sprintf("by the `%s` workflow", m.Workflow))
	}
	if m.SHA != "" {
		parts = append(parts, fmt.Sprintf("from `%s`", shortSHA(m.SHA)))
	}
	if !m.When.IsZero() {
		parts = append(parts, fmt.Sprintf("on %s", m.When.UTC().Format("2006-01-02")))
	}
	if len(parts) == 0 {
		return ""
	}
	return "_Generated " + strings.Join(parts, " ") + "._\n"
}

// shortSHA abbreviates a full git SHA to its first seven characters, leaving
// already-short or non-hex values untouched.
func shortSHA(sha string) string {
	if len(sha) > 7 {
		return sha[:7]
	}
	return sha
}
